### ISSUE TITLE
comen在线版本链接字段缺失

### ISSUE THREAD

**Issue by BAKAOLC** [3Shain/Comen#69]
comen在线版本，bilibili方面无法正常运作
对比老版本的自动转化链接发现缺少&bilichat=字段，补上后可正常运行
不知是特性还是尚未处理的bug
（老版本的自动转化链接如删去&bilichat=字段也会导致无法正常运作）

**Comment by 3Shain** [comment]
这是一个暂时的workaround。因为现阶段在线服务的主要目的是提供bilichat原有用户兼容的过渡阶段，而非兼容相关的部分目前是未完全实现的状态（并且也没有正式地发布过）。所以正常用户应当是按照之前bilichat的使用方式以正常转化到兼容模式。

但非兼容模式（或者说是原生模式）基本使用应该是正常的，只是目前不像bilichat一样会有提示，评论也是自顶向下开始渲染的。

由于现在bilichat的域名是直接解析到了comen的服务上，可能会造成一些困惑，我会采取点暂时性的措施。
