### ISSUE TITLE
一些关于Comen未来的功能实现上的疑问

### ISSUE THREAD

**Issue by PianCat** [3Shain/Comen#81]
Q1：Comen是否后续会增加自动翻译到日语/英语的功能（采用公开API进行翻译）。示例：隔壁项目：https://github.com/xfgryujk/blivechat
Q2：Comen未来会有气泡类型的样式制作器吗？或者说更多元化类型的样式制作器。

**Comment by PianCat** [comment]
来自VUP同时是个大DD的疑问

**Comment by 3Shain** [comment]
A1: 不是目前的主要目标
A2: 会有。这是正在做的内容（beta分支）

个人精力有限，需要的是时间。
